### ISSUE TITLE
Unable to execute tests in docker

### ISSUE THREAD

**Issue by Shelex** [goosik/cypress-test#6]
Following the instructions from e2e/README I am unable to run tests in docker because of error.
<details>
<summary>Console output</summary> 
<pre>
Oleksandr:e2e shelex$ docker build -t crew-app .
Sending build context to Docker daemon  17.92kB
Step 1/3 : FROM cypress/base
latest: Pulling from cypress/base
4b105072aa89: Pull complete 
b775667b1fd0: Pull complete 
0fe156bcb4b1: Pull complete 
fb9906355a0f: Pull complete 
880a3b83482f: Pull complete 
228e101c8671: Pull complete 
f77ff8405034: Pull complete 
cd091f7b9743: Pull complete 
f26d34c61f97: Pull complete 
e783dfd71987: Pull complete 
Digest: sha256:184a63af0e7ae6201aeeca9de655079bb8f095b0d75d57be5b09537935f57426
Status: Downloaded newer image for cypress/base:latest
 ---> 8a80da34cc4a
Step 2/3 : RUN npm install
 ---> Running in e5a0682f72a6
npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#2 No description
npm WARN !invalid#2 No repository field.
npm WARN !invalid#2 No README data
npm WARN !invalid#2 No license field.

up to date in 0.697s
found 0 vulnerabilities

Removing intermediate container e5a0682f72a6
 ---> 4b5d2307ecbf
Step 3/3 : RUN $(npm bin)/cypress run
 ---> Running in 494a039d2595
/bin/sh: 1: /node_modules/.bin/cypress: not found
The command '/bin/sh -c $(npm bin)/cypress run' returned a non-zero code: 127
</pre>
</details>

Could you please assist how to solve this?

**Comment by goosik** [comment]
Am I right, that you tried to run 'docker build -t crew-app .' command inside **e2e** folder?
Anyway, I changed Dockerfile and docker-compose.yml, so now there shouldn't be an error

**Comment by Shelex** [comment]
Thank you for answer.
Now I am running docker-compose and got such error:
<details>
<summary>Console output</summary> 
<pre>
Oleksandr:e2e shelex$ pwd
/.../cypress-test/e2e
Oleksandr:e2e shelex$ docker-compose up --exit-code-from cypress
WARNING: using --exit-code-from implies --abort-on-container-exit
Building cypress
ERROR: Cannot locate specified Dockerfile: ./e2e/cypress/Dockerfile.cypress
</pre>
</details>

**Comment by Shelex** [comment]
After fix https://github.com/goosik/cypress-test/commit/118fa9cc99619cf545d39a78776bbce3fd3c0ee9 you have kindly provided it is working now as expected 👍
