### ISSUE TITLE
Cypress not detecting e2e folder

### ISSUE THREAD

**Issue by Shelex** [goosik/cypress-test#7]
When I follow the [steps from readme](https://github.com/goosik/cypress-test/blob/master/e2e/README.md#installation) Cypress opens the default spec files list automatically generated by cypress and I don't see spec files from `./e2e/cypress/integration/`: [Folder Structure](https://api.monosnap.com/file/download?id=lncSBe1GQAVVRrxGilwQb4EJf7tY0W) and [Cypress Runner](https://api.monosnap.com/file/download?id=DMi8QqfVQA4ybhC28HcLXFmm5Sk440)

**Comment by goosik** [comment]
yes, you are right! changed  'open cypress' command with adding '--project e2e' flag

**Comment by Shelex** [comment]
Now tests from `e2e` are running, thanks!
